services:
  backend-api:
    build: ./backend-api
    container_name: backend-api
    ports:
      - "3000:3000"
    depends_on:
      - backend-sql  # ✔️ Depende del nombre del servicio, NO de la ruta
    networks:
      - sqlnet

  backend-sql:
    build: ./backend/sql  # ✔️ Ruta corregida a donde realmente está tu código
    container_name: backend-sql
    ports:
      - "5000:5000"
    networks:
      - sqlnet

networks:
  sqlnet:
    driver: bridge
