version: '3.9'

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - OAUTHLIB_INSECURE_TRANSPORT=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
